### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by sxre** [IOKernel/Sangatsu#7]
still get an error

```
C:\Users\rpcdr\Desktop\Sangatsu-master>python sangatsu.py
Traceback (most recent call last):
  File "C:\Users\rpcdr\Desktop\Sangatsu-master\sangatsu.py", line 24, in <module>
Exception in thread Thread-1 (background):
Traceback (most recent call last):
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    main()
  File "C:\Users\rpcdr\Desktop\Sangatsu-master\sangatsu.py", line 12, in main
    engine = gm.start_engine()
  File "C:\Users\rpcdr\Desktop\Sangatsu-master\utils\game.py", line 32, in start_engine
    engine = chess.engine.SimpleEngine.popen_uci(os.path.join(SCRIPT_DIR, 'bin', 'stockfish'))
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2387, in popen_uci
    self.run()
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 174, in background
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2379, in popen
    loop.run_until_complete(asyncio.gather(*pending, loop=loop, return_exceptions=True))
TypeError: gather() got an unexpected keyword argument 'loop'
    return run_in_background(background, debug=debug)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 186, in run_in_background
    return future.result()
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 165, in background
    loop.run_until_complete(coroutine(future))
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2369, in background
    simple_engine = cls(transport, protocol, timeout=timeout)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2270, in __init__
    self.shutdown_event = asyncio.Event(loop=self.protocol.loop)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 168, in __init__
    super().__init__(loop=loop)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001A9EB07B250>
Traceback (most recent call last):
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001A9EB090D30>
Traceback (most recent call last):
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 115, in __del__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001A9EB090D30>
Traceback (most recent call last):
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 115, in __del__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001A9EB090D30>
Traceback (most recent call last):
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 115, in __del__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
```

**Comment by IOKernel** [comment]
Hmm, I haven't tested the new version on Windows yet, I'll check it out tomorrow and fix it.

**Comment by sxre** [comment]
Alright, thanks man!

**Comment by sxre** [comment]
works fine i did a little more digging and it turned out the error was due to me having a very old version of the chess module

**Comment by IOKernel** [comment]
> me

Oh, perfect then.

I was having my own set of errors on windows regarding paths, but my windows installation is very modified and messed up so I guess that's why

**Comment by sxre** [comment]
i did fix the deprecation issues regarding firefox so it can work ill send the file and you can see if it fixes anything.


```py
def start_driver(username, password):
    # create a new Firefox session
    #profile = webdriver.FirefoxProfile()
    ## profile.set_preference("general.useragent.override", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0")
    #profile.set_preference("general.useragent.override", "Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0")
    #driver = webdriver.Firefox(profile, executable_path=os.path.join(SCRIPT_DIR, 'bin', 'geckodriver'))
    profile_path = r'C:\Users\rpcdr\AppData\Roaming\Mozilla\Firefox\Profiles\7ca8o7yv.default'
    options=Options()
    options.binary_location = r"C:\Program Files\Mozilla Firefox/firefox.exe"
    options.add_argument("--start-maximized")
    options.set_preference('profile', profile_path)
    service = Service(executable_path=os.path.join(SCRIPT_DIR, 'bin', 'geckodriver'))
    driver = webdriver.Firefox(service=service, options=options)
    driver.get('https://www.chess.com/login')
    # login
    # wait for username field to be visible
    username_field = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, "username"))
    )
    # enter username
    username_field.send_keys(username)
    # wait for password field to be visible
    password_field = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, "password"))
    )
    # enter password and login
    password_field.send_keys(password)
    password_field.send_keys(Keys.RETURN)
    time.sleep(8)
    driver.get("https://www.chess.com/play/online")
    return driver
```

just replace my paths with your paths
everyone's default profile is different so you'll have to get that and replace it. lmk how it goes!
